name: Publish to NPM

# on:
#   workflow_dispatch:
#     inputs:
#       version:
#         description: 'Specify the version to publish'
#         required: true

on:
  push:
    branches:
      - workflow

jobs:
  publish:
    uses: DioryMe/.github/.github/workflows/publish-npm.yml@main
    with:
      version: '1.2.3'
      # version: ${{ github.event.inputs.version }}
